### ISSUE TITLE
[Suggestion] Combine elytra with jetpacks.

### ISSUE THREAD

**Issue by ImCoolYeah105** [Tomson124/SimplyJetpacks-2#19] opened 2017-01-04 01:19 UTC
With the introduction of the elytra in minecraft, I think that it would be very cool to be able to combine the two so you can soar through the skies endlessly.

**Comment by thundr** [comment] 2018-06-28 00:17
Duplicate of #34

**Closed** 2018-06-28 00:17 UTC
Labels: enhancement
